2016-11-22 11:21:49.891 +03:00 [Debug] Hosting starting
2016-11-22 11:21:50.005 +03:00 [Debug] Hosting started
2016-11-22 11:22:15.524 +03:00 [Debug] Connection id ""0HL0IM2LCPJH9"" started.
2016-11-22 11:22:15.622 +03:00 [Information] Request starting HTTP/1.1 POST http://localhost:5000/api/puzzle/photo/111 application/json 107
2016-11-22 11:22:15.644 +03:00 [Debug] "POST" requests are not supported
2016-11-22 11:22:15.834 +03:00 [Debug] Request successfully matched the route with name '"user"' and template '"api/puzzle/photo/{id}"'.
2016-11-22 11:22:15.884 +03:00 [Debug] Executing action "Puzzle.WebApi.Controllers.PhotoController.Post (Puzzle.WebApi)"
2016-11-22 11:22:16.264 +03:00 [Debug] Opening connection to database 'puzzle_test' on server 'mysqlinstance.ci0jfdlf2czl.us-west-2.rds.amazonaws.com'.
2016-11-22 11:22:18.426 +03:00 [Debug] Closing connection to database 'puzzle_test' on server 'mysqlinstance.ci0jfdlf2czl.us-west-2.rds.amazonaws.com'.
2016-11-22 11:22:18.436 +03:00 [Debug] Opening connection to database 'puzzle_test' on server 'mysqlinstance.ci0jfdlf2czl.us-west-2.rds.amazonaws.com'.
2016-11-22 11:22:19.035 +03:00 [Information] Executed DbCommand (68ms) [Parameters=[], CommandType='Text', CommandTimeout='30']
SELECT COUNT(*) FROM INFORMATION_SCHEMA.TABLES WHERE TABLE_SCHEMA = 'puzzle_test'
2016-11-22 11:22:19.040 +03:00 [Debug] Closing connection to database 'puzzle_test' on server 'mysqlinstance.ci0jfdlf2czl.us-west-2.rds.amazonaws.com'.
2016-11-22 11:22:19.690 +03:00 [Error] Connection id ""0HL0IM2LCPJH9"": An unhandled exception was thrown by the application.
System.Reflection.TargetInvocationException: Exception has been thrown by the target of an invocation. ---> Amazon.Runtime.AmazonClientException: No RegionEndpoint or ServiceURL configured
   at Amazon.Runtime.ClientConfig.Validate() in E:\JenkinsWorkspaces\v3-stage-release\AWSDotNetPublic\sdk\src\Core\Amazon.Runtime\ClientConfig.cs:line 417
   at Amazon.S3.AmazonS3Config.Validate() in E:\JenkinsWorkspaces\v3-stage-release\AWSDotNetPublic\sdk\src\Services\S3\Custom\AmazonS3Config.cs:line 67
   at Amazon.Runtime.AmazonServiceClient..ctor(AWSCredentials credentials, ClientConfig config) in E:\JenkinsWorkspaces\v3-stage-release\AWSDotNetPublic\sdk\src\Core\Amazon.Runtime\AmazonServiceClient.cs:line 152
   --- End of inner exception stack trace ---
   at System.RuntimeMethodHandle.InvokeMethod(Object target, Object[] arguments, Signature sig, Boolean constructor)
   at System.Reflection.RuntimeConstructorInfo.Invoke(BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
   at Amazon.Extensions.NETCore.Setup.ClientFactory.CreateClient(Type serviceInterfaceType, AWSCredentials credentials, ClientConfig config) in D:\Jenkins\jobs\v3-stage-release\workspace\AWSDotNetPublic\extensions\src\AWSSDK.Extensions.NETCore.Setup\ClientFactory.cs:line 83
   at Microsoft.Extensions.DependencyInjection.ServiceProvider.ScopedCallSite.Invoke(ServiceProvider provider)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.ConstructorCallSite.Invoke(ServiceProvider provider)
   at Microsoft.Extensions.DependencyInjection.ServiceProvider.TransientCallSite.Invoke(ServiceProvider provider)
   at Microsoft.Extensions.Internal.ActivatorUtilities.GetService(IServiceProvider sp, Type type, Type requiredBy, Boolean isDefaultParameterRequired)
   at lambda_method(Closure , IServiceProvider , Object[] )
   at Microsoft.AspNetCore.Mvc.Internal.TypeActivatorCache.CreateInstance[TInstance](IServiceProvider serviceProvider, Type implementationType)
   at Microsoft.AspNetCore.Mvc.Controllers.DefaultControllerFactory.CreateController(ControllerContext context)
   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.<InvokeAllActionFiltersAsync>d__26.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.<InvokeExceptionFilterAsync>d__25.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.<InvokeAsync>d__18.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.AspNetCore.Builder.RouterMiddleware.<Invoke>d__4.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Swashbuckle.SwaggerUi.Application.SwaggerUiMiddleware.<Invoke>d__5.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Swashbuckle.SwaggerUi.Application.RedirectMiddleware.<Invoke>d__4.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Swashbuckle.Swagger.Application.SwaggerMiddleware.<Invoke>d__6.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.AspNetCore.Hosting.Internal.RequestServicesContainerMiddleware.<Invoke>d__3.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.AspNetCore.Server.Kestrel.Internal.Http.Frame`1.<RequestProcessingAsync>d__2.MoveNext()
2016-11-22 11:22:19.733 +03:00 [Information] Request finished in 4133.1529ms 200 
2016-11-22 11:22:19.772 +03:00 [Debug] Connection id ""0HL0IM2LCPJH9"" completed keep alive response.
2016-11-22 11:23:18.545 +03:00 [Debug] Hosting shutdown
2016-11-22 11:23:18.558 +03:00 [Debug] Connection id ""0HL0IM2LCPJH9"" disconnecting.
2016-11-22 11:23:18.560 +03:00 [Debug] Connection id ""0HL0IM2LCPJH9"" sending FIN.
2016-11-22 11:23:18.565 +03:00 [Debug] Connection id ""0HL0IM2LCPJH9"" sent FIN with status "0".
2016-11-22 11:23:18.568 +03:00 [Debug] Connection id ""0HL0IM2LCPJH9"" stopped.
